#!/bin/sh

# Usage:
# ./deploy-vagrant

if (/usr/local/bin/vagrant status | grep "default.*not created (virtualbox)"); then
  time /usr/local/bin/vagrant up
else
  time /usr/local/bin/vagrant provision
fi
