FROM base

# Install prerequisites for {{container_name}}
RUN apt-get -y install \
  build-essential \
  bzip2 \
  fxload \
  libftdi-dev \
  libqt4-dev \
  libusb-1.0-0-dev \
  tar

# Download, build and install {{container_name}}
RUN apt-get -y install wget
RUN wget http://downloads.sourceforge.net/project/linguider/4.1.0/lin_guider-4.1.0.tar.bz2
RUN bunzip2 lin_guider-4.1.0.tar.bz2
RUN tar xf lin_guider-4.1.0.tar
RUN cd ./lin_guider_pack/lin_guider && ./configure
RUN cd ./lin_guider_pack/lin_guider && make -j $(grep -c ^processor /proc/cpuinfo)

# Install graphical environment
RUN apt-get -y install \
  websockify \
  x11vnc \
  xvfb

# Needed at runtime for websockify
RUN apt-get -y install \
  python-pip

# Create a script to run our full graphical environment.
RUN echo "#!/usr/bin/env sh" > /start.sh
RUN echo "/usr/bin/Xvfb :{{xdisplay}} -screen 0 {{xwindow_width}}x{{xwindow_height}}x16 &" >> /start.sh
RUN echo "/usr/bin/x11vnc -display :{{xdisplay}} -N -forever &" >> /start.sh
RUN echo "/usr/bin/websockify {{websockify_port}} localhost:{{vnc_port}} &" >> /start.sh
RUN echo "DISPLAY=:{{xdisplay}} {{exec}}" >> /start.sh
RUN echo "" >> /start.sh
RUN chmod +x /start.sh

EXPOSE {{vnc_port}}
EXPOSE {{websockify_port}}

CMD ["/start.sh"]
