{% if ansible_machine == "x86_64" -%}
  FROM debian:jessie
{% elif ansible_machine == "armv7l" -%}
  FROM resin/rpi-raspbian:jessie-20160831
{% else -%}
  # No docker base available for architecture: {{ansible_machine}}
{% endif %}
RUN apt-get -y update

RUN apt-get -y install \
  git \
  nodejs-legacy \
  npm

RUN npm install -g elm

RUN mkdir -p /stage
COPY git /stage

EXPOSE 8000

WORKDIR /stage

CMD ["elm-reactor", "-p", "8000", "-a", "0.0.0.0"]
