---

################################
# Ansible-Docker Prerequisites #
################################

- name: Install apt dependencies
  apt: name={{item}} state=installed
  with_items:
    - python-setuptools
  become: true

- name: Install pip
  easy_install:
    name: pip
  become: true

- name: Install python dependencies
  pip:
    name: docker-py
  become: true

######################################
# Build our Application Docker Image #
######################################

- name: Create staging area for {{service_name}} docker image
  file:
    recurse: true
    path: /tmp/Docker/{{service_name}}
    state: directory
    mode: 0755

- name: Generate Dockerfile for {{service_name}} docker image
  template:
    src: templates/Dockerfile.j2
    dest: /tmp/Docker/{{service_name}}/Dockerfile
    mode: 0644

- name: Install git
  apt: name=git state=installed
  become: true

- name: Download latest code for {{service_name}}
  git:
    repo: "{{git_repo}}"
    dest: /tmp/Docker/{{service_name}}/git
    depth: 1
    accept_hostkey: true
    force: true
  # Remove after https://github.com/ansible/ansible-modules-core/issues/5504 is fixed
  register: git_deploy
  until: git_deploy|succeeded

- name: Build {{service_name}} docker image
  docker_image:
    name: "{{service_name}}"
    path: /tmp/Docker/{{service_name}}
    pull: false
    force: true
  become: true

- name: Run {{service_name}} service via docker container
  docker_container:
    name: "{{service_name}}"
    image: "{{service_name}}"
    pull: false
    published_ports:
      - "{{public_web_port}}:80"
    restart_policy: "{{restart_policy}}"
    state: "{{container_state}}"
  become: true
