FROM debian:jessie
RUN apt-get -y update

RUN apt-get -y install \
  git \
  net-tools \
  python \
  wget

RUN wget https://github.com/novnc/noVNC/archive/v0.6.1.tar.gz
RUN gunzip v0.6.1.tar.gz
RUN tar xf v0.6.1.tar

EXPOSE {{websockify_port}}

CMD ["/noVNC-0.6.1/utils/launch.sh", "--listen", "{{websockify_port}}"]
