FROM base

# Install prerequisites for {{container_name}}
RUN apt-get -y install \
  build-essential \
  cmake \
  libindi-dev \
  libnova-dev \
  libwxgtk3.0-dev \
  pkg-config \
  wx-common \
  wx3.0-i18n \
  zlib1g-dev

# Download, build and install {{container_name}}
RUN apt-get -y install git
RUN git clone --depth 1 https://github.com/OpenPHDGuiding/phd2.git /phd2
RUN mkdir /phd2/tmp
RUN cd /phd2/tmp && cmake ..
RUN cd /phd2/tmp && make -j $(grep -c ^processor /proc/cpuinfo)
RUN cd /phd2/tmp && make install

# Install graphical environment
RUN apt-get -y install \
  websockify \
  x11vnc \
  xvfb

# Needed at runtime for websockify
RUN apt-get -y install \
  python-pip

# Create a script to run our full graphical environment.
RUN echo "#!/usr/bin/env sh" > /start.sh
RUN echo "/usr/bin/Xvfb :{{xdisplay}} -screen 0 {{xwindow_width}}x{{xwindow_height}}x16 &" >> /start.sh
RUN echo "/usr/bin/x11vnc -display :{{xdisplay}} -N -forever &" >> /start.sh
RUN echo "/usr/bin/websockify {{websockify_port}} localhost:{{vnc_port}} &" >> /start.sh
RUN echo "DISPLAY=:{{xdisplay}} {{exec}}" >> /start.sh
RUN echo "" >> /start.sh
RUN chmod +x /start.sh

EXPOSE {{vnc_port}}
EXPOSE {{websockify_port}}

CMD ["/start.sh"]
